version: '3.8'

services:
  iptvx-server:
    build: .
    container_name: iptvx-media-server
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /mediaserver/iptvx-server/config/:/config
    environment:
      - TZ=America/Chicago # Set to your local time zone
